version: '3.9'

services:
    vue:
        build: ./vue
        ports:
            - "8080:8080"
        volumes:
            - ./vue/src:/vue/src
            - ./vue/package.json:/vue/package.json
        environment:
            - VUE_APP_SERVER_IP=cardgameamm.duckdns.org

    backend:
        build: ./express
        ports:
            - "8002:8001"
        volumes:
            - ./express/src:/express/src
            - ./express/package.json:/express/package.json

