version: '3.9'

services:
    vue:
        build: ./vue
        ports:
            - "9999:8080"
        volumes:
            - ./vue/src:/vue/src
            - ./vue/package.json:/vue/package.json
    backend:
        build: ./express
        ports:
            - "8000:8000"
        volumes:
            - ./express/src:/express/src
            - ./express/package.json:/express/package.json
